//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDetail
    {
        public int Mail_ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> StudentUserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
